# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# https://developer.android.com/studio/command-line for more details.
# For more details on how to configure your build environment visit
# https://developer.android.com/studio/build/configure-build-environment

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does nothing about the resources declared in
# any upstream library.
# This property is particularly useful for library development and publishing.
android.useNamespace=true
android.enableJetifier=true
android.useAndroidX=true
android.enableDexingArtifactTransform=true
